services:
  - type: web
    name: naver-automation
    env: python
    buildCommand: |
      # Python 의존성 먼저 설치
      pip install -r requirements.txt
      
      # 시스템에서 Chrome 찾기 시도
      echo "=== Chrome 바이너리 검색 중 ==="
      find /usr -name "*chrome*" -type f 2>/dev/null | head -10 || echo "시스템에서 Chrome을 찾을 수 없음"
      which google-chrome-stable || echo "google-chrome-stable을 찾을 수 없음"
      which google-chrome || echo "google-chrome을 찾을 수 없음"
      which chromium-browser || echo "chromium-browser를 찾을 수 없음"
      
      # 환경 정보 출력
      echo "=== 환경 정보 ==="
      uname -a
      cat /etc/os-release || echo "OS 정보를 읽을 수 없음"
      echo "사용자: $(whoami)"
      echo "권한: $(id)"
    startCommand: "python server.py"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: DISPLAY
        value: :99
      - key: RENDER
        value: true
      - key: NAVER_ID
        value: your_naver_id
      - key: NAVER_PW
        value: your_naver_password